const glossaryAllTerms = [
  {
    term: "AASHTO Manual",
    definition:
      "The term 'AASHTO Manual' means the American Association of State Highway and Transportation Officials (AASHTO) 'Manual for Bridge Evaluation' with Sections 1.4, 2.2, 4.2, 6, and 8, excluding the 3rd paragraph in Article 6B.7.1.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "AASHTO MBEI",
    definition:
      "AASHTO Manual for Bridge Element Inspection is a reference for standardized element definitions, element quantity calculations, condition state definitions, element feasible actions, and inspection conventions. This manual is used for element descriptions, quantity calculations, and condition state definitions.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Abrasion",
    definition: "Wearing or grinding away of material by water containing sand, gravel, or stones.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Abrasive Condition",
    definition: "The presence of granular material accompanied with a stream gradient or flow sufficient to cause movement of the granular material in the streambed.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Anchor",
    definition:
      "A tendon, tendon bundle, rod, or bar element that is installed into the ground through the wall and anchored into stable material well behind potentially unstable soil, then tensioned and attached to the wall to provide additional resistance to earth pressures. Anchors are also referred to as Tie-Backs or Ground Anchors.",
    search: `What is "Anchor" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Annual Average Daily Traffic (AADT)",
    definition: "The total annual volume of traffic passing a point or segment of a highway in both directions divided by the number of days in a year.",
    search: `What is "Annual Average Daily Traffic" in transportation engineering?`,
    discipline: "transportation engineering",
    page: ["glossary-bridge-tab", "bridge-alignment-pg5"],
  },
  {
    term: "Annual Average Daily Truck Traffic (AADTT)",
    definition: "The total annual volume of truck traffic passing a point or segment of a highway in both directions divided by the number of days in a year.",
    search: `What is "Annual Average Daily Truck Traffic" in transportation engineering?`,
    discipline: "transportation engineering",
    page: ["glossary-bridge-tab", "bridge-alignment-pg5"],
  },
  {
    term: "Approach Roadway Alignment",
    definition:
      "The portion of the roadway leading up to a bridge, consisting of horizontal and vertical curves and grades. It provides a predictable path for drivers and ensures a smooth, safe transition to the bridge. Properly constructed approach roadways minimize abrupt changes in direction or slope, maintaining vehicle comfort and safety.",
    discipline: "bridge design",
    page: "bridge-alignment-pg5",
  },
  {
    term: "Arch Ring",
    definition: "The curved, topmost portion of an arch that carries the compressive load across the span of the bridge, ensuring structural stability.",
    search: ``,
    discipline: "arch design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Backwall",
    definition: "The vertical wall at the rear of an abutment that retains the roadway fill behind a bridge.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Backwater",
    definition: "The increase in the upstream water elevation resulting from an obstruction to flow, such as a bridge and/or embankment placed in the floodplain.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Barrel",
    definition: "The main body of a culvert structure that transports water beneath the roadway.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Bin Wall",
    definition:
      "A type of gravity retaining wall consisting of bins typically fabricated from metal or concrete, filled with granular soil material, and then placed adjacent and atop of one another. The individual bins are typically placed in a non-interlocking manner.",
    search: `What is "Bin Wall" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Blistering",
    definition: "Process of water infiltrating the first layer of a fiberglass-reinforced plastic large culvert structure causing bubbles to form near the surface.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Bridge",
    definition:
      "A structure including supports erected over a depression or an obstruction, such as water, highway, or railway, and having a track or passageway for carrying traffic or other moving loads, and having an opening measured along the center of the roadway of more than 20 feet between under copings of abutments or spring lines of arches, or extreme ends of openings for multiple boxes; it includes multiple pipes, where the clear distance between openings is less than half of the smaller contiguous opening.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Bridge Elements",
    definition:
      "Individual parts of a bridge that are subsets of bridge components, inventoried separately as functional groups. Elements inventoried on the bridge include: the total quantity for each element, and the element quantity that exists in each of four condition states reported to the NBI in accordance with 23 U.S.C. 144(d)(2).",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Bridge Inspector’s Reference Manual",
    definition:
      "A comprehensive FHWA manual on procedures and techniques for inspecting and evaluating a variety of in-service highway bridges. This manual is available at: https://www.fhwa.dot.gov/bridge/nbis.cfm.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Cantilever Semi-Gravity",
    definition:
      "A type of retaining wall that has a vertical stem wall that is structurally connected to a base slab, or footing. The base slab may be either bearing directly on underlying foundation soil or supported on piles. The vertical stem wall is typically reinforced concrete or reinforced, solid-grouted concrete masonry block, while the base slab is reinforced concrete. The combined weight of the retaining wall itself and the soil mass on the base slab provides overall stability against earth pressures, while the stem wall behaves as a vertical cantilever member that is reinforced at the base of the wall providing cantilever resistance to lateral earth pressures.",
    search: `What is "Cantilever Semi-Gravity" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Centerline",
    definition:
      "The yellow painted line, or the imaginary line, that separates traffic moving in opposite directions on a roadway. It serves as a visual guide for drivers, indicating the boundary between lanes of traffic going in opposite directions.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab", "bridge-alignment-pg5"],
  },
  { term: "Channel", definition: "A waterway used to transport water from one location to another.", search: ``, discipline: "bridge design", page: ["glossary-culvert-tab"] },
  {
    term: "Clear Zone",
    definition: "The area along a roadway that is kept free of obstacles, designed to provide a safe space for vehicles that leave the road.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Closed Median",
    definition: "A median in which the area between the two roadways on the structure is bridged over and is capable of supporting traffic.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Complex Feature",
    definition:
      "Bridge component(s) or member(s) with advanced or unique structural members or operational characteristics, construction methods, and/or requiring specific inspection procedures. This includes mechanical and electrical elements of movable spans and cable-related members of suspension and cable-stayed superstructures.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Corrosion",
    definition: "Deterioration or dissolution of a material by chemical or electrochemical reaction with the surrounding environment.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Cover",
    definition: "The depth of backfill present between the top of a culvert structure and the base layer of the roadway.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Crash Wall",
    definition: "A reinforced protective wall built around bridge piers or critical infrastructure to absorb and deflect vehicle impacts.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Crest Vertical Curve",
    definition: "A curve in the roadway profile that connects an ascending grade to a descending grade, typically used to smooth transitions at the crest of a hill.",
    discipline: "bridge design",
    page: "bridge-alignment-pg5",
  },
  {
    term: "Crib Wall",
    definition:
      "A type of gravity retaining wall consisting of interlocking elements of timber, metal, or precast concrete arranged in the form of bins (or cribwork) and filled with granular soil material. Crib walls gain their stability not only from their weight but also to some extent from the strength of fill within the bins.",
    search: `What is "Crib Wall" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Cross Bracing",
    definition: "A system of diagonal braces used to strengthen and stabilize the bridge structure, typically placed between girders or beams.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Cross-Section",
    definition: "A view or diagram representing a vertical or horizontal cut through an object, structure, or terrain to show internal features.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Cross Slope",
    definition: "The slope of the roadway surface perpendicular to the direction of travel, designed to allow for proper drainage of water.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab", "bridge-alignment-pg5"],
  },
  {
    term: "Crossover",
    definition:
      "A designated area or path, often a short roadway, that allows vehicles to cross a median or divider to access opposing roadways or areas. Crossovers are commonly found on divided highways or interstates to provide access between different sides of the road.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab", "bridge-alignment-pg5"],
  },
  {
    term: "Crosswalk",
    definition:
      "A designated area on a road or street, marked to provide a safer path for pedestrians to cross. It typically consists of painted lines or markings to make the crossing more visible to drivers.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab", "bridge-alignment-pg5"],
  },
  {
    term: "Culvert",
    definition:
      "A structure comprised of one or more barrels, beneath an embankment and designed structurally to account for soil-structure interaction. These structures are hydraulically and structurally designed to convey water, sediment, debris, and, in many cases, aquatic and terrestrial organisms through roadway embankments. Culvert barrels have many sizes and shapes and have inverts that are either integral or open, i.e. supported by spread or pile-supported footings. Many culverts take advantage of headwater submergence of the inlet to increase hydraulic efficiency and economy.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab", "glossary-culvert-tab"],
  },
  {
    term: "Curve Length",
    definition: "The length of a curved section of the roadway or bridge, typically measured along the centerline.",
    discipline: "bridge design",
    page: "bridge-alignment-pg5",
  },
  {
    term: "Damage Inspection",
    definition: "An unscheduled inspection to assess structural damage resulting from environmental factors or human actions.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Deflection",
    definition: "Change in the original or specified vertical or horizontal measurement of a culvert structure.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Delamination",
    definition: "Separation of a layer of concrete generally through internal cracking parallel to the concrete surface.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Deterioration",
    definition: "Decline in quality over time due to chemical or physical wearing.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Designated Lead State",
    definition:
      "The State responsible for reporting the full bridge record for a border bridge. The Designated Lead State and Neighboring State are determined through agreement between the two border States.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  { term: "Differential Settlement", definition: "Uneven settlement between footings or supports.", search: ``, discipline: "bridge design", page: ["glossary-culvert-tab"] },
  {
    term: "Divided Highway",
    definition: "A highway with separated roadways for traffic traveling in opposite directions.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Double Deck Bridge",
    definition:
      "A bridge consisting of two decks, tiers, or levels. These bridges may incorporate highway lanes on both levels or highway lanes on one level and other transportation modes on the other level.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Downspout",
    definition: "A drainage component that directs water from the bridge deck to a designated drainage system.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Downstream",
    definition:
      "The direction in which water flows away from the source or higher elevation. In engineering, it refers to structures, impacts, or conditions occurring after the point of interest in the flow path.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Drilled Shaft",
    definition:
      "A structural element constructed using an auger to drill into a soil mass to remove soil and then filling the drilled void with concrete. Drilled shafts used for retaining wall construction are typically built as Secant Walls (consisting of overlapping or intersecting drilled shafts), Soldier Walls (consisting of spaced drilled shafts with lagging), or Tangent Walls (consisting of drilled shafts placed side-by-side and touching one another, but not overlapping).",
    search: `What is "Drilled Shaft" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Driver Expectation",
    definition:
      "Relates to the likelihood that a driver will respond to common situations in predictable ways that the driver has found successful in the past. A driver’s readiness to respond to situations, events, and information in predictable and successful ways.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Earthwork",
    definition: "The process of moving, excavating, or compacting soil, rock, or other materials to prepare a site for construction or engineering projects.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Eastbound, Westbound, Northbound, Southbound",
    definition: "Moving in the indicated direction, typically referring to traffic lanes or transportation routes.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Efflorescence",
    definition:
      "A deposit on concrete, brick, stone, or mortar caused by crystallization of carbonates brought to the surface by moisture in the masonry or concrete. Efflorescence is a combination of calcium carbonate leached out of the cement paste and other recrystallized carbonate and chloride compounds.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab", "glossary-culvert-tab"],
  },
  {
    term: "Element Level Bridge Inspection Data",
    definition: "Quantitative condition assessment data, collected during bridge inspections, that indicates the severity and extent of defects in bridge elements.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Embankment",
    definition: "Soil constructed above the natural ground surface that encases a culvert structure and supports a roadway.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Engineered Wood",
    definition:
      "Products that utilize veneers, plywood, reconstituted wood panel products, or engineered wood assemblies. Some engineered wood products include glued laminated timber, I-joists, and laminated veneer lumber.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  { term: "Erosion", definition: "The removal of a material or surface over time by flowing water.", search: ``, discipline: "bridge design", page: ["glossary-culvert-tab"] },
  {
    term: "Exfiltration",
    definition: "The process of water exiting a culvert structure and entering the surrounding soil through unintended openings.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Federal Information Processing Series (FIPS)",
    definition:
      "A system of numeric and/or alphabetic coding issued by the National Institute of Standards and Technology (NIST), an agency of the US Department of Commerce. FIPS codes are assigned for a variety of geographic entities including American Indian and Alaska Native Areas, Hawaiian home lands, congressional districts, counties, county subdivisions, metropolitan areas, places, and states. FIPS codes were discontinued by NIST in 2005, but the Census Bureau continues to maintain and issue codes for the geographic entities covered.",
    source: "http://www.fhwa.dot.gov/bridge/nbi.cfm",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Federal Lands",
    definition:
      "Lands under the jurisdiction of Federal agencies. FHWA’s Federal Land Management Agency partners currently include: National Park Service (NPS); USDA Forest Service (Forest Service); U.S. Fish and Wildlife Service (USFWS); Bureau of Indian Affairs (BIA) and Tribal Governments; Bureau of Land Management (BLM); Department of Defense (DOD); U.S. Army Corps of Engineers (USACE); and Bureau of Reclamation (BOR).",
    source: "https://highways.dot.gov/federal-lands/about",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Ferry Transfer Bridge",
    definition: "A bridging structure that enables vehicular movement from a dock or approach roadway to a ferry.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Fiber Reinforced Polymer Composite (FRP)",
    definition:
      "Also known as fiberglass reinforced plastic, FRP is a composite made from glass fiber or carbon fiber reinforcement in a plastic (polymer) matrix. With reinforcement of the plastic matrix, a wide variety of physical strengths and properties can be designed into the material. Additionally, the type and configuration of the reinforcement can be selected, along with the type of polymer and additives within the matrix.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Flexible Culvert",
    definition: "A culvert that relies on a consistent application of pressure from the surrounding soil envelope to develop structural strength.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Floating Bridge",
    definition: "A bridge supported by floating on pontoons moored to the lakebed or riverbed; a portion may be removable to facilitate navigation.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Floodplain",
    definition: "The flat, often expansive area adjacent to a channel that is subject to periodic flooding, typically formed by sediment deposition during high-water events.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Flow Line",
    definition: "The lowest point within a channel, pipe, or culvert where water is expected to flow under normal conditions.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Freeboard",
    definition: "The clearance between the bottom of the superstructure and the design high-water elevation.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Gabion",
    definition:
      "A cage, wire container, cylinder, or similar type box filled with rocks, broken concrete, or granular soil used in retaining wall and erosion control applications.",
    search: `What is "Gabion" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  { term: "Galvanization", definition: "Application of zinc coating along the surface of a structure.", search: ``, discipline: "bridge design", page: ["glossary-culvert-tab"] },
  {
    term: "Gravity Wall",
    definition:
      "A wall typically built with stone masonry, mass concrete, or other heavy material that depends on its overall mass, or weight, to resist earth pressure from behind.",
    search: `What is "Gravity Wall" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Groundwater",
    definition: "Water located beneath the Earth's surface in soil pores and rock formations, supplying wells and springs.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Hands-On Inspection",
    definition: "Inspection within arm’s length of the member. Inspection uses visual techniques that may be supplemented by nondestructive evaluation techniques.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Headwall",
    definition: "A retaining wall at the end of a culvert or bridge opening that stabilizes the structure and prevents erosion.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Highway",
    definition:
      "The term 'highway' includes: A) a road, street, and parkway; B) a right-of-way, bridge, railroad-highway crossing, tunnel, drainage structure, sign, guardrail, and protective structure, in connection with a highway; and C) a portion of any interstate or international bridge or tunnel and the approaches thereto, the cost of which is assumed by a State transportation department, including such facilities as may be required by the United States Customs and Immigration Services in connection with the operation of an international bridge or tunnel.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Highway Performance Monitoring System (HPMS)",
    definition:
      "A national level highway information system that includes data on the extent, condition, performance, use, and operating characteristics of the nation's highways.",
    source: "http://www.fhwa.dot.gov/policyinformation/hpms/fieldmanual/",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Horizontal Alignment",
    definition: "The layout of the roadway in the horizontal plane, including curves, tangents, and transitions.",
    discipline: "bridge design",
    page: "bridge-alignment-pg5",
  },
  {
    term: "Horizontal Curve Radius",
    definition: "The radius of a curve in the roadway or bridge, determining the sharpness or gentleness of the curve.",
    discipline: "bridge design",
    page: "bridge-alignment-pg5",
  },
  {
    term: "Hydraulic Review",
    definition:
      "A review by a person qualified to evaluate the field-observed hydraulic conditions and make a determination of the impacts of the conditions on the performance of the channel, channel protection, or when working with structural staff, determine the scour vulnerability of a bridge member or entire bridge. Hydraulic reviews may include a review of the field inspection notes and photographs, review of as-built plans, scour appraisals, and scour POAs, or performance of a hydraulic analysis as deemed appropriate.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "In-Depth Inspection",
    definition:
      "A close-up, detailed inspection of one or more bridge members located above or below water, using visual or nondestructive evaluation techniques as required to identify any deficiencies not readily detectable using routine inspection procedures. Hands-on inspection may be necessary at some locations. In-depth inspections may occur more or less frequently than routine inspections, as outlined in bridge-specific inspection procedures.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Infiltration",
    definition: "The process of water or backfill material entering the culvert structure through unintended openings.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Inherent Defect",
    definition:
      "Not indicative of damage or deterioration but is either a characteristic of the material or the result of normal construction practices. Examples include insignificant width fabrication, shrinkage, and temperature cracks, pop-outs, or shallow edge chips and spalls.",
    search: `What is an "Inherent Defect" in bridge design?`,
    discipline: "bridge design",
    page: [["glossary-defects-tab"]],
  },
  {
    term: "Initial Inspection",
    definition:
      "The first inspection of a new, replaced, or rehabilitated bridge. This inspection serves to record required bridge inventory data, establish baseline conditions, and establish the intervals for other inspection types.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  { term: "Inlet", definition: "The initial 5 ft of the upstream end of a culvert structure.", search: ``, discipline: "bridge design", page: ["glossary-culvert-tab"] },
  {
    term: "Inspection Date",
    definition: "The date on which the field portion of the bridge inspection is completed.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Inspection Due Date",
    definition: "The last inspection date plus the current inspection interval.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Inspection Report",
    definition: "The document which summarizes the bridge inspection findings, recommendations, and identifies the team leader responsible for the inspection and report.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Internal Redundancy",
    definition:
      "A redundancy that exists within a primary member cross-section without load path redundancy, such that fracture of one component will not propagate through the entire member, is discoverable by the applicable inspection procedures, and will not cause a portion of or the entire bridge to collapse.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Inventory Data",
    definition: "All data reported to the National Bridge Inventory in accordance with the Specifications for the National Bridge Inventory.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  { term: "Invert", definition: "The bottom or lowest region along the internal surface of a pipe.", search: ``, discipline: "bridge design", page: ["glossary-culvert-tab"] },
  {
    term: "Isolated Defects",
    definition: "Defect is visible in one or few incident locations.",
    search: `What are "Isolated Defects" in bridge inspection?`,
    discipline: "bridge inspection",
    page: [["glossary-defects-tab"]],
  },
  {
    term: "Jobsite",
    definition: "A location where construction, maintenance, or engineering work is actively taking place.",
    search: ``,
    discipline: "transportation engineering",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Joint",
    definition: "Connection where two sections of a culvert structure meet. Additional material may be present to ensure a watertight connection between sections.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Keystone",
    definition: "The central, topmost stone or concrete block of an arch that locks the other blocks or sections in place, crucial for the arch’s structural integrity.",
    search: ``,
    discipline: "arch design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Lagging",
    definition:
      "Structural members that are typically timber, steel, or concrete that are installed behind, between or in front of piles or drilled shafts to support and retain the soil material between spaced piles. Timber lagging is typically used for temporary construction while steel or concrete lagging is typically used for permanent construction.",
    search: `What is "Lagging" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "LaPorte",
    definition: "The INDOT district name and county name are written as one word with a capital P: LaPorte. The city name is written as two words: La Porte.",
    search: `INDOT LaPorte District`,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
    link: `https://entapps.indot.in.gov/dotmaps/districtmaps/`,
  },
  {
    term: "Large Culvert",
    definition: "A culvert structure with a measured span length between 4 ft and 20 ft as measured perpendicular to the centerline of the parent roadway.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Legal Load",
    definition:
      "The maximum load for each vehicle configuration, including the weight of the vehicle and its payload, permitted by law for the State in which the bridge is located.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Legal Load Rating",
    definition:
      "The maximum permissible legal load to which the structure may be subjected with the unlimited numbers of passages over the duration of a specified bridge evaluation period. Legal load rating is a term used in Load and Resistance Factor Rating method.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Line of Sight",
    definition: "The unobstructed view along the roadway, crucial for driver safety, allowing the driver to see upcoming curves or obstacles.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab", "bridge-alignment-pg5"],
  },
  {
    term: "Load-Bearing",
    definition: "A structural element, such as a wall or beam, that supports and transfers loads from above to the foundation or other supporting members.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Load Path Redundancy",
    definition:
      "A redundancy that exists based on the number of primary load-carrying members between points of support, such that fracture of the cross-section at one location of a member will not cause a portion of or the entire bridge to collapse.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Load Posting",
    definition:
      "Regulatory signs installed in accordance with the 'Manual on Uniform Traffic Control Devices' and State or local law which represent the maximum vehicular live load which the bridge may safely carry.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Legally Enforceable Load Posting",
    definition: "Posting of a load restriction sign (or signs) at a bridge in accordance with State law that is legally enforceable by law enforcement personnel.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Linear Referencing System (LRS)",
    definition:
      "Provides a geospatial representation of a road network through a set of procedures for determining and retaining a record of specific points along a highway. Typical methods used are mile point, milepost, reference point, or link node. LRS data are required for the annual Highway Performance Monitoring System (HPMS) data submittal from the States to FHWA.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Load Rating",
    definition:
      "The analysis to determine the safe vehicular live load carrying capacity of a bridge using bridge plans and supplemented by measurements and other information gathered from an inspection.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Major Defect",
    definition:
      "Damage or deterioration is significant, and the strength or performance is adversely affected. Examples would be similar in type to moderate defects but of greater magnitude and severity that, upon reporting, would require a structural or geotechnical review.",
    search: `What is a "Major Defect" in bridge inspection?`,
    discipline: "bridge inspection",
    page: [["glossary-defects-tab"]],
  },
  {
    term: "Major Rehabilitation",
    definition: "The major work required to restore the structural integrity or serviceability of a bridge as well as work necessary to correct major safety defects.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Mecahnically Stabilzed Earth (MSE) Wall",
    definition:
      "Mechanically stabilized earth, sometimes referred to as reinforced soil, is a soil mass embankment constructed with artificial reinforcing that typically consist of either geosynthetics or steel material. When used as retaining walls, MSE walls are designed as gravity walls built with multiple layers of horizontal reinforcing in granular backfill connected to wall face components.",
    search: `What is "MSE" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Minor Defect",
    definition:
      "Damage or deterioration has initiated but is not considered significant. Examples include minimal to moderate width cracks with no efflorescence or rust stains, shallow depth spalls with no exposed reinforcing steel, or speckled surface rust.",
    search: `What is a "Minor Defect" in bridge inspection?`,
    discipline: "bridge inspection",
    page: [["glossary-defects-tab"]],
  },
  {
    term: "Minor Rehabilitation",
    definition:
      "The minor work required to preserve or restore the structural integrity of a bridge or serviceability as well as the work necessary to correct minor safety defects.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Moderate Defect",
    definition:
      "Damage or deterioration is significant, but the strength or performance is not yet adversely affected. Examples include moderate width cracks with either efflorescence or rust stains, spalls with exposed reinforcing steel, or more pronounced surface rust and corrosion with either pitting or delamination. Defects or deterioration at this level may not yet warrant a structural or geotechnical review.",
    search: `What is a "Moderate Defect" in bridge inspection?`,
    discipline: "bridge inspection",
    page: [["glossary-defects-tab"]],
  },
  {
    term: "Modular Block Wall",
    definition:
      "A gravity wall built using interlocking blocks that are typically masonry, concrete, or concrete masonry units (CMU) to resist earth pressure from behind. Some modular block walls may also use artificial reinforcing similar to MSE walls.",
    search: `What is "Modular Block Wall" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Multi-level Interchange",
    definition:
      "A multilevel highway intersection or junction of intersecting roads and bridges arranged so that vehicles may move from one road to another without crossing the streams of traffic.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "National Bridge Inspection Standards (NBIS)",
    definition:
      "Federal regulations establishing national policy regarding bridge inspection organization, bridge inspection frequency, inspector qualifications, inventory requirements, report formats, and inspection and rating procedures, as described in 23 CFR 650 Subpart C.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "National Bridge Inventory (NBI)",
    definition:
      "An aggregation of State transportation department, Federal agency and Tribal government bridge and associated highway data maintained by the Federal Highway Administration (FHWA). The NBIS requires each State transportation department, Federal agency, and Tribal government to prepare and maintain a bridge inventory, which must be submitted to FHWA in accordance with these specifications on an annual basis or whenever requested.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "National Highway Freight Network (NHFN)",
    definition:
      "A national highway freight network established by FHWA to assist States in strategically directing resources toward improved movement of freight on highways. The NHFN consists of a Primary Highway Freight System, the portions of the Interstate System not designated as part of the Primary Highway Freight System, and Critical Rural Freight Corridors and Critical Urban Freight Corridors designated by states.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Nationally Certified Bridge Inspector",
    definition: "An individual meeting the team leader requirements of 23 CFR 650.309(b).",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Navigable Waterway",
    definition:
      "Navigable waterways are determined by the Commandant of the United States Coast Guard. Title 33 of the Code of Federal Regulations, Section 2.36, defines navigable waterways as consisting of territorial seas of the United States, internal waters subject to tidal influence, and internal waters not subject to tidal influence that are used for interstate or foreign commerce or determined capable of improvement for such use.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Neighboring State",
    definition:
      "The State responsible for reporting an abbreviated bridge record for a border bridge. The Designated Lead State and the Neighboring State are determined through agreement between the two border States.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Nominal",
    definition: "Referring to an approximate or standard value, typically used when the exact measurement may vary slightly but is considered close to the stated value.",
    search: ``,
    discipline: "bridge design",
    page: ["bridge-deck-pg11"],
  },
  {
    term: "Nonredundant Steel Tension Member (NSTM)",
    definition:
      "A primary steel member fully or partially in tension, and without load path redundancy, system redundancy, or internal redundancy, whose failure may cause a portion of or the entire bridge to collapse.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Nonredundant Steel Tension Member (NSTM) Inspection",
    definition: "A hands-on inspection of a nonredundant steel tension member.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Off-Ramp",
    definition: "A roadway that allows vehicles to exit a highway or freeway.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab", "bridge-alignment-pg5"],
  },
  {
    term: "On-Ramp",
    definition: "A roadway that allows vehicles to enter a highway or freeway.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab", "bridge-alignment-pg5"],
  },
  {
    term: "Operating Rating",
    definition:
      "The maximum permissible live load to which the structure may be subjected for the load configuration used in the load rating. Allowing unlimited numbers of vehicles to use the bridge at operating level may shorten the life of the bridge. Operating rating is a term used in either Allowable Stress or Load Factor Rating method.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Orthotropic Deck",
    definition:
      "An orthotropic deck consists of a flat, thin steel plate stiffened by a series of closely spaced longitudinal ribs at right angles to the floor beams. The deck acts integrally with the steel superstructure.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  { term: "Outlet", definition: "The final 5 ft of the downstream end of a culvert structure.", search: ``, discipline: "bridge design", page: ["glossary-culvert-tab"] },
  {
    term: "Overpass",
    definition: "A bridge or elevated structure that allows a road, railway, or pedestrian path to cross over another roadway or obstacle.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Pile",
    definition: "A structural element driven or drilled into the ground to resist vertical and/or horizontal loads. Piles are usually rolled steel shapes, concrete, or timber.",
    search: `What is "Pile" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Piping",
    definition: "The process of erosion along the exterior perimeter of a culvert barrel.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Post-Tensioned",
    definition: "A type of concrete construction where the concrete is tensioned after it has been poured, typically using steel tendons to enhance its strength.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  { term: "Pressure Head", definition: "Height of water above a plane or point of reference.", search: ``, discipline: "bridge design", page: ["glossary-culvert-tab"] },
  {
    term: "Private Bridge",
    definition: "A bridge open to public travel and not owned by a public authority as defined in 23 U.S.C. 101.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Procedures",
    definition:
      "Written documentation of policies, methods, considerations, criteria, and other conditions that direct the actions of personnel so that a desired end result is achieved consistently.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Probability",
    definition:
      "Extent to which an event is likely to occur during a given interval. This may be based on the frequency of events, such as in the quantitative probability of failure, or on degree of belief or expectation. Degrees of belief about probability can be chosen using qualitative scales, ranks, or categories such as, remote, low, moderate, or high.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Program Manager",
    definition:
      "The individual in charge of the program, that has been assigned the duties and responsibilities for bridge inspection, reporting, and inventory, and has the overall responsibility to ensure the program conforms with the requirements of the NBIS as provided in 23 CFR 650 Subpart C. The program manager provides overall leadership and is available to inspection team leaders to provide guidance.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Public Road",
    definition: "As defined in 23 U.S.C. 101(a)(21) as any road or street under the jurisdiction of and maintained by a public authority and open to public travel.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Quality Assurance (QA)",
    definition:
      "The use of sampling and other measures to assure the adequacy of quality control procedures in order to verify or measure the quality level of the entire bridge inspection and load rating program.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Quality Control (QC)",
    definition: "Procedures that are intended to maintain the quality of a bridge inspection and load rating at or above a specified level.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Railroad",
    definition: "A system of tracks along which trains are guided, often including the associated infrastructure like stations and bridges.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Railroad Flat Car",
    definition: "A salvaged flatbed railroad car used as a bridge superstructure, typically on low-volume roads. This type of bridge often has NSTMs.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Rebar",
    definition: "Short for 'reinforcing bar,' a steel bar used to strengthen concrete structures by providing tensile support.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Rehabilitation",
    definition: "Repairing a culvert to return it to its initial condition or better.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Replacement",
    definition: "Total replacement of a structure with a new facility constructed in the same general traffic corridor.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab", "glossary-culvert-tab"],
  },
  {
    term: "Retaining Wall",
    definition:
      "A permanent, relatively rigid structure that supports a soil mass at slopes steeper than their angle of rest to provide usable space both above and in front of the wall.",
    search: `What is "Retaining Wall" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Right-of-Way",
    definition:
      "The land designated for the roadway and its components, including the traveled way, shoulders, and any additional space required for construction and maintenance.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab", "bridge-alignment-pg5"],
  },
  {
    term: "Rigid Culvert",
    definition: "A culvert that relies on internal material properties to develop structural strength.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Riprap",
    definition: "Loose stone or rock material placed along embankments, shorelines, or riverbeds to prevent erosion.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Risk",
    definition:
      "The exposure to the possibility of structural safety or serviceability loss during the interval between inspections. It is the combination of the probability of an event and its consequence.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Roadside",
    definition: "The area adjacent to the edge of a roadway, often including shoulders, ditches, and vegetation.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Roadway",
    definition: "The portion of a highway, including shoulders, for vehicular use. A divided highway has two or more roadways.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Route",
    definition: "A specific road, highway, or travel way open to public travel.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Routine Inspection",
    definition:
      "Regularly scheduled comprehensive inspection consisting of observations and measurements needed to determine the physical and functional condition of the bridge and identify changes from previously recorded conditions.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Routine Permit Load",
    definition:
      "A live load, which has a gross weight, axle weight, or distance between axles not conforming with State statutes for legally configured vehicles, authorized for unlimited trips over an extended period of time to move alongside other heavy vehicles on a regular basis.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Safe Load Capacity",
    definition: "A live load that can safely utilize a bridge repeatedly over the duration of a specified inspection interval.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Sag Vertical Curve",
    definition: "A curve in the roadway profile that connects a descending grade to an ascending grade, typically used to smooth transitions at the bottom of a dip or valley.",
    discipline: "bridge design",
    page: "bridge-alignment-pg5",
  },
  {
    term: "Scaling",
    definition: "Disintegration of cement paste caused by chemical attacks or freeze-thaw cycles that erode the concrete surface.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Scour",
    definition: "Erosion of streambed or bank material due to flowing water; often considered as being localized around piers and abutments of bridges.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab", "glossary-culvert-tab"],
  },
  {
    term: "Scour Appraisal",
    definition:
      "A risk-based and data-driven determination of a bridge’s vulnerability to scour, resulting from the least stable result of scour that is either observed, or estimated through a scour evaluation or a scour assessment.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Scour Assessment",
    definition:
      "The determination of an existing bridge’s vulnerability to scour which considers stream stability and scour potential as described in HEC 20 and other scour-related data sources.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Scour Critical Bridge",
    definition: "A bridge with a foundation member that is unstable, or may become unstable, as determined by the scour appraisal.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Scour Evaluation",
    definition:
      "The application of hydraulic analysis as described in HEC 18 and HEC 20 to estimate scour depths and determine bridge and substructure stability considering potential scour.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Scour Monitoring Inspection",
    definition:
      "An inspection performed during or after a triggering storm event as required by a Scour Plan of Action (POA), by personnel with qualifications required by the agency.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Scour Plan of Action (POA)",
    definition: "Procedures for bridge inspectors and engineers in managing each bridge determined to be scour critical or that has unknown foundations.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Section Loss",
    definition: "Loss of a material’s thickness caused by chemical or physical degradation.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Service Inspection",
    definition: "An inspection to identify major deficiencies and safety issues, performed by personnel with general knowledge of bridge maintenance or bridge inspection.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Sheet Pile Wall",
    definition:
      "A cantilever wall built using interlocking plate piles fabricated from pressed or molded steel sheet metal to provide structural resistance to lateral earth pressures. Such walls can be fully cantilevered or include anchors for additional resistance.",
    search: `What is "Sheet Pile Wall" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Sidewalk",
    definition: "A paved path for pedestrians along the side of a roadway, typically made of concrete or asphalt.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Slabbing",
    definition: "Straightening of rounded concrete sections accompanied by cracking and/or spalls.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Slipforming",
    definition:
      "A construction method where concrete is poured continuously into a form that is gradually moved upwards as the concrete hardens. This technique is commonly used for constructing barrier walls. Horizontal cracking can sometimes occur over time due to shrinkage, temperature changes, or the weight of the concrete during curing. If the curing process isn't properly controlled, or if there is uneven setting or stress distribution, it can lead to the formation of cracks along the horizontal plane of the wall.",
    search: ``,
    discipline: "barrier wall design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Slopewall",
    definition: "A protective concrete or riprap covering placed on embankments to prevent soil erosion near bridges and culverts.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Snowdrift",
    definition: "A deep accumulation of snow formed by wind movement and deposition.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Snowplow",
    definition: "A vehicle or equipment used to remove snow from roadways and highways.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Snowstorm",
    definition: "A weather event characterized by heavy snowfall and reduced visibility.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Soil Envelope",
    definition: "Soil or backfill encasing a culvert structure and applying pressure due to the weight of the soil.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Soil Nails",
    definition: "Steel rods providing soil reinforcement into embankments that are either grouted into drilled holes or driven into soil at close spacing.",
    search: `What is "Soil Nails" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Soldier Pile Wall",
    definition:
      "A cantilever wall built using piles, typically rolled steel shapes and installed at regular intervals (nominally 6 to 10 foot spacings) to provide structural resistance to lateral earth pressures. Lagging is then placed between the soldier piles to both support and retain the soil material between piles and to transfer those lateral earth pressures to the soldier piles. Such walls can be fully cantilevered or include anchors for additional resistance.",
    search: `What is "Soldier Pile Wall" in retaining wall design?`,
    discipline: "retaining wall design",
    page: ["glossary-wall-tab"],
  },
  {
    term: "Some Defects",
    definition: "Defect visibility is more than isolated and less than widespread.",
    search: `What are "Some Defects" in bridge inspection?`,
    discipline: "bridge design",
    page: [["glossary-defects-tab"]],
  },
  { term: "Spalling", definition: "Separation of surface concrete due to fractures within the material.", search: ``, discipline: "bridge design", page: ["glossary-culvert-tab"] },
  {
    term: "Special Inspection",
    definition:
      "An inspection scheduled at the discretion of the bridge owner, used to monitor a particular known or suspected deficiency, or to monitor special details or unusual characteristics of a bridge that does not necessarily have defects.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Springline",
    definition:
      "The horizontal line at which the arch ring begins to curve from the abutment, marking the transition between the arch ring and the abutments. The horizontal distance between two springlines is the span distance.",
    search: ``,
    discipline: "arch design",
    page: ["glossary-culvert-tab", "glossary-compounds-tab"],
  },
  {
    term: "State",
    definition: "Any of the 50 States, the District of Columbia, or Puerto Rico.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "State Transportation Department",
    definition: "That department, commission, board, or official of any State charged by its laws with the responsibility for highway construction.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Stormwater",
    definition: "Water from precipitation that flows over surfaces and is managed through drainage systems to prevent flooding and erosion.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Strategic Highway Network (STRAHNET) Connectors",
    definition: "Highways which provide access between major military installations and highways which are part of the Strategic Highway Network.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Strategic Highway Network (STRAHNET)",
    definition:
      "A network of highways which are important to the United States' strategic defense policy and which provide defense access, continuity, and emergency capabilities for defense purposes.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Structural Review",
    definition:
      "A review by a person qualified to evaluate the field-observed conditions and make a determination of the impacts of the conditions on the performance of the bridge member or entire bridge. Structural reviews may include a review of the field inspection notes and photographs, review of as-built plans, or analysis as deemed appropriate.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Subdistrict",
    definition: "A smaller administrative division within a larger district, often used in transportation planning.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
    link: `https://entapps.indot.in.gov/dotmaps/districtmaps/`,
  },
  {
    term: "Superelevation",
    definition: "The banking of the roadway at curves to counteract centrifugal force and improve vehicle stability.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab", "bridge-alignment-pg5"],
  },
  {
    term: "Supported Bridge",
    definition:
      "A bridge with temporary shoring, supports, repairs, or supplemental members that are installed to keep the bridge open despite deficiencies in the permanent structure, pending future repairs or replacement.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "System Redundancy",
    definition:
      "A redundancy that exists in a bridge system without load path redundancy, such that fracture of the cross-section at one location of a primary member will not cause a portion of or the entire bridge to collapse.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Team Leader",
    definition:
      "The on-site, nationally certified bridge inspector in charge of an inspection team and responsible for planning, preparing, performing, and reporting on bridge field inspections.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Temporary Bridge",
    definition: "A bridge which is constructed to carry highway traffic until the permanent facility is built, repaired, rehabilitated, or replaced.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Transition Curve",
    definition: "A curve that gradually changes the curvature of the road to provide a smoother transition between straight and curved sections.",
    discipline: "bridge design",
    page: "bridge-alignment-pg5",
  },
  {
    term: "Traveled Way",
    definition: "The portion of roadway for the movement of vehicles, exclusive of shoulders.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Underdrain",
    definition: "A drainage system placed below the surface of the ground to remove excess water and prevent soil erosion or saturation.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Underground",
    definition: "Refers to structures or utilities located below the surface, such as tunnels, pipelines, or electrical wiring.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Undermining",
    definition: "Erosion process that removes material from below and threatens the structural integrity of the above member; typically occurs around footings and other supports.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Underpass",
    definition: "A passage that allows vehicles, pedestrians, or water to travel beneath a road, railway, or other obstruction.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Underwater Bridge Inspection Diver",
    definition: "The individual performing the inspection of the underwater portion of the bridge.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Underwater Inspection",
    definition:
      "Inspection of the underwater portion of a bridge substructure and the surrounding channel, which cannot be inspected visually at low water or by wading or probing, and generally requiring diving or other appropriate techniques.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Unknown Foundations",
    definition:
      "Foundations of bridges over waterways where complete details are unknown because either the foundation type and depth are unknown, or the foundation type is known, but its depth is unknown, and therefore cannot be appraised for scour vulnerability.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-bridge-tab"],
  },
  {
    term: "Upstream",
    definition:
      "The direction opposite to the flow of water in a river, stream, or drainage system, moving toward the source or higher elevation. In engineering, it refers to structures, impacts, or conditions occurring before the point of interest in the flow path.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Vertical Alignment",
    definition: "The configuration of the roadway in the vertical plane, including grades, curves, and elevations.",
    discipline: "bridge design",
    page: "bridge-alignment-pg5",
  },
  {
    term: "Vertical Curve",
    definition: "A curve in the vertical alignment of the roadway, typically used to transition between different grades.",
    discipline: "bridge design",
    page: "bridge-alignment-pg5",
  },
  {
    term: "Vertical Grade",
    definition: "The slope or incline of the roadway along the vertical plane, expressed as a percentage.",
    discipline: "bridge design",
    page: "bridge-alignment-pg5",
  },
  {
    term: "Vertical Offset",
    definition: "Displacement of an object from its original position in the vertical direction.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-culvert-tab"],
  },
  {
    term: "Waterline",
    definition: "The elevation or mark indicating the typical level of water in a stream, river, or other water body near a structure.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Watershed",
    definition: "An area of land that drains all precipitation and runoff to a common outlet, such as a river, bay, or other body of water.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
  {
    term: "Widespread Defects",
    definition: "Defect is visible across many incident locations.",
    search: `What are "Widespread Defects" in bridge inspection?`,
    discipline: "bridge inspection",
    page: [["glossary-defects-tab"]],
  },
  {
    term: "Wingwall",
    definition: "A sidewall extending from an abutment or headwall that helps retain soil and direct water flow away from a bridge or culvert.",
    search: ``,
    discipline: "bridge design",
    page: ["glossary-compounds-tab"],
  },
];

// "glossary-bridge-tab", "glossary-culvert-tab", "glossary-defects-tab", "glossary-wall-tab", "glossary-compounds-tab", "bridge-alignment-pg5"
